blog/urls.py
from django.conf.urls import url
from . import views

app_name = "blog"
urlpatterns = [

    url(r"^$",views.IndexView.as_view(),name="index"),
    url(r"^index$",views.IndexView.as_view(),name="index"),
    url(r"^index.html$",views.IndexView.as_view(),name="index"),
    # url(r"^posts/(?P<pk>\d+)$",views.details,name="details"),
    url(r"^posts/(?P<pk>\d+)$",views.PostDetailView.as_view(),name="details"),
    # http://127.0.0.1:8000/blog/archives/2020/5
    # url(r"^archives/(?P<year>\d{4})/(?P<month>\d{1,2})$",views.archive,name="archive"),
    url(r"^archives/(?P<year>\d{4})/(?P<month>\d{1,2})$",views.ArchiveView.as_view(),name="archive"),
    url(r"^categories/(?P<pk>\d+)$",views.CategoryView.as_view(),name="category"),
    # url(r"^tags/(?P<pk>\d+)$",views.tag,name="tag"),
    url(r"^tags/(?P<pk>\d+)$",views.TagView.as_view(),name="tag"),
    # url(r"^search/",views.search,name="search"),

]

templates/base.html
<!DOCTYPE html>
<html>
{% load static %}
{% load blog_extras %}
<head>
    <title>二十八画生博客</title>
    <!-- meta -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- css -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <link rel="stylesheet" href="{% static 'blog/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'blog/css/pace.css' %}">
    <link rel="stylesheet" href="{% static 'blog/css/custom.css' %}">
    <link href="https://cdn.bootcss.com/highlight.js/9.15.8/styles/github.min.css" rel="stylesheet">


    <!-- js -->

    <script src="{% static 'blog/js/jquery-2.1.3.min.js' %}"></script>
    <script src="{% static 'blog/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'blog/js/pace.min.js' %}"></script>
    <script src="{% static 'blog/js/modernizr.custom.js' %}"></script>


    <!-- js -->
    <style>
        .codehilite {
          padding: 0;
        }

        /* for block of numbers */
        .hljs-ln-numbers {
          -webkit-touch-callout: none;
          -webkit-user-select: none;
          -khtml-user-select: none;
          -moz-user-select: none;
          -ms-user-select: none;
          user-select: none;

          text-align: center;
          color: #ccc;
          border-right: 1px solid #CCC;
          vertical-align: top;
          padding-right: 5px;
        }

        .hljs-ln-n {
          width: 30px;
        }

        /* for block of code */
        .hljs-ln .hljs-ln-code {
          padding-left: 10px;
          white-space: pre;
        }
        /* 搜索关键词高亮 */
        span.highlighted {
          color: red;
        }
    </style>


</head>
{% if messages %}
    {% for message in messages %}
      <div class="alert alert-{{ message.tags }} alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span
                aria-hidden="true">&times;</span></button>
        {{ message }}
      </div>
    {% endfor %}
{% endif %}
<body>


<div class="container">
    <header id="site-header">
        <div class="row">
            <div class="col-md-4 col-sm-5 col-xs-8">
                <div class="logo">
                    <h1><a href="{% url 'blog:index' %}"><b>二十八画生</b> </a></h1>
                </div>
            </div><!-- col-md-4 -->
            <div class="col-md-8 col-sm-7 col-xs-4">
                <nav class="main-nav" role="navigation">
                    <div class="navbar-header">
                        <button type="button" id="trigger-overlay" class="navbar-toggle">
                            <span class="ion-navicon"></span>
                        </button>
                    </div>

                    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                        <ul class="nav navbar-nav navbar-right">
                            <li class="cl-effect-11"><a href="{% url 'blog:index' %}" data-hover="首页">首页</a></li>
                            <li class="cl-effect-11"><a href="{% url 'blog:index' %}" data-hover="博客">博客</a></li>
                            <li class="cl-effect-11"><a href="{% url 'blog:index' %}" data-hover="关于">关于</a></li>
                            <li class="cl-effect-11"><a href="{% url 'blog:index' %}" data-hover="联系">联系</a></li>
                            <li class="cl-effect-11"><a href="/test" data-hover="资源">资源</a></li>
                        </ul>
                    </div><!-- /.navbar-collapse -->
                </nav>
                <div id="header-search-box">
                    <a id="search-menu" href="#"><span id="search-icon" class="ion-ios-search-strong"></span></a>
                    <div id="search-form" class="search-form">
                        <form role="search" method="get" id="searchform" action="{% url 'haystack_search' %}">
                            <input type="search" name = "q" placeholder="搜索" required>
                            <button type="submit"><span class="ion-ios-search-strong"></span></button>
                        </form>
                    </div>
                </div>
            </div><!-- col-md-8 -->
        </div>
    </header>
</div>
<div class="copyrights">Collect from <a href="http://www.cssmoban.com/">网页模板</a></div>
<div class="copyrights">Modified by <a href="">二十八画生修改</a></div>

<div class="content-body">
    <div class="container">
        <div class="row">
            <main class="col-md-8">
                  {% block main %}
                  {% endblock main %}
            </main>
            <aside class="col-md-4">
                  {% block toc %}
                  {% endblock toc %}

                  {% show_recent_posts 4 %}
                  {% show_archives %}
                  {% show_categories %}
                  {% show_tags %}

                  <div class="rss">
                        <a href="{% url 'rss' %}"><span class="ion-social-rss-outline"></span> RSS 订阅</a>
                  </div>
            </aside>
        </div>
    </div>
</div>

<footer id="site-footer">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <p class="copyright">&copy 2017 - 采集自<a href="http://www.cssmoban.com/"
                                                        target="_blank" title="模板之家">模板之家</a>
                    - 由<a href="" title="网页模板" target="_blank">二十八画生</a>修改
                </p>
            </div>
        </div>
    </div>
</footer>

<!-- Mobile Menu -->
<div class="overlay overlay-hugeinc">
    <button type="button" class="overlay-close"><span class="ion-ios-close-empty"></span></button>
    <nav>
        <ul>
            <li><a href="{% url 'blog:index' %}">首页</a></li>
            <li><a href="{% url 'blog:index' %}">博客</a></li>
            <li><a href="{% url 'blog:index' %}">关于</a></li>
            <li><a href="{% url 'blog:index' %}">联系</a></li>
            <li><a href="{% url 'test' %}">资源</a></li>
        </ul>
    </nav>
</div>


<script src="{% static 'blog/js/script.js' %}"></script>

<script src="https://cdn.bootcss.com/highlight.js/9.15.8/highlight.min.js"></script>
<script src="https://cdn.bootcss.com/highlightjs-line-numbers.js/2.7.0/highlightjs-line-numbers.min.js"></script>
<script>
    hljs.initHighlightingOnLoad();
    hljs.initLineNumbersOnLoad();
</script>
</body>
</html>

templates/test1.html
<!DOCTYPE html>
<html lang="zh-CN">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- 上述3个meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->
    <title>资源库</title>

    <!-- Bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css" rel="stylesheet">
<!--    <link rel="stylesheet" type="text/css" href="css/index.css"/>-->
</head>
<body>
<!-- 导航 -->
<nav class="navbar navbar-default">
	<div class="container-fluid">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<a class="navbar-brand" href="#" style="margin: 0 0;padding: 0 0;">
				<img src="" style="margin-top: 5px;" height="40px">
			</a>
		</div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li><a href="index.html">首页<span class="sr-only">(current)</span></a></li>
                <li class="active"><a href="#">资源库</a></li>
				<li><a href="#">共享链接</a></li>
            </ul>
        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>

<div class="container-fluid">

    <!-- 面包屑导航 -->
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
        </ol>
    </nav>
	<div class="alert alert-info" role="alert">书山有路勤为径,学海无涯苦作舟</div>
    <!-- 列表组 -->
    <ul class="list-group">
		{% if dirlist %}
			{% for i in dirlist %}
			<li class="list-group-item">
				<span class="glyphicon glyphicon-save-file" aria-hidden="true"></span>
				<a href="/math?name={{ i }}">{{ i }}</a>
			</li>
			{% endfor %}
		{% endif %}
    </ul>
</div>
<footer class="footer">
	<hr>
	<div class="row align-items-center justify-content-md-between">
		<div class="col-md-12">
			<ul class="nav nav-footer justify-content-end">
				<div class="nav-item" style="text-align: center;">
				<a href="http://www.beian.miit.gov.cn/" class="nav-link text-center" target="_blank"></a>
				</div>
			</ul>
		</div>
	</div>
</footer>

<!-- jQuery (Bootstrap 的所有 JavaScript 插件都依赖 jQuery，所以必须放在前边) -->
<script src="https://cdn.jsdelivr.net/npm/jquery@1.12.4/dist/jquery.min.js"></script>
<!-- 加载 Bootstrap 的所有 JavaScript 插件。你也可以根据需要只加载单个插件。 -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/js/bootstrap.min.js"></script>
<!--<script src="js/index.js"></script>-->
</body>
</html>