blog/urls.py
from django.conf.urls import url
from . import views

app_name = "blog"
urlpatterns = [

    url(r"^$",views.IndexView.as_view(),name="index"),
    url(r"^index$",views.IndexView.as_view(),name="index"),
    url(r"^index.html$",views.IndexView.as_view(),name="index"),
    # url(r"^posts/(?P<pk>\d+)$",views.details,name="details"),
    url(r"^posts/(?P<pk>\d+)$",views.PostDetailView.as_view(),name="details"),
    # http://127.0.0.1:8000/blog/archives/2020/5
    # url(r"^archives/(?P<year>\d{4})/(?P<month>\d{1,2})$",views.archive,name="archive"),
    url(r"^archives/(?P<year>\d{4})/(?P<month>\d{1,2})$",views.ArchiveView.as_view(),name="archive"),
    url(r"^categories/(?P<pk>\d+)$",views.CategoryView.as_view(),name="category"),
    # url(r"^tags/(?P<pk>\d+)$",views.tag,name="tag"),
    url(r"^tags/(?P<pk>\d+)$",views.TagView.as_view(),name="tag"),
    # url(r"^search/",views.search,name="search"),

]

comment/urls.py
from django.conf.urls import url
from . import views


app_name="comment"

urlpatterns = [
    url(r"^(?P<post_pk>\d+)$",views.comment,name="comment"),
]

comment/models.py
from django.db import models
from django.utils import timezone
from blog.models import Post

# Create your models here.

class Comment(models.Model):

    name = models.CharField(max_length=50,verbose_name="名字")
    email = models.EmailField(verbose_name="邮箱")
    url = models.URLField(verbose_name="网址",blank=True)
    text = models.TextField(verbose_name="评论")
    create_time = models.DateTimeField(verbose_name="创建时间",default=timezone.now())
    post = models.ForeignKey("blog.Post",verbose_name="文章",on_delete=models.CASCADE)

    class Meta:
        db_table = "comment"
        verbose_name = "评论"
        verbose_name_plural = verbose_name

    def __str__(self):

        return "{}:{}".format(self.name,self.text[:20])

comment/forms.py
from django import forms
from .models import Comment


class CommentForms(forms.ModelForm):

    class Meta:

        model = Comment
        fields = ["name","email","url","text"]

comment/views.py
from django.shortcuts import render,HttpResponse,redirect
from blog.models import Post
from .forms import CommentForms
from django.views.decorators.http import require_POST
from django.contrib import messages


# Create your views here.

@require_POST
def comment(request,post_pk):
    try:
        post = Post.objects.get(pk=post_pk)
    except Exception as e:
        print(e)
        return render(request,"blog/404.html")
    print(request.POST)
    form = CommentForms(request.POST)
    #检查form表单是否合法
    if form.is_valid():
        comment = form.save(commit=False)
        comment.post = post
        comment.save()
        messages.add_message(request,messages.SUCCESS,"评论发表成功",extra_tags="sucess")
        url = "/blog/posts/%s"%(post_pk)
        return redirect(url)
    context={"post":post,"form":form}
    messages.add_message(request, messages.ERROR, '评论发表失败！请修改表单中的错误后重新提交。', extra_tags='danger')
    return render(request,"comment/preview.html",locals())

templates/comment/inclusions/_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form action="{% url 'comment:comment' post.pk %}" method="post" class="comment-form">
  {% csrf_token %}
  <div class="row">
    <div class="col-md-4">
      <label for="{{ form.name.id_for_label }}">{{ form.name.label }}：</label>
      {{ form.name }}
      {{ form.name.errors }}
    </div>
    <div class="col-md-4">
      <label for="{{ form.email.id_for_label }}">{{ form.email.label }}：</label>
      {{ form.email }}
      {{ form.email.errors }}
    </div>
    <div class="col-md-4">
      <label for="{{ form.url.id_for_label }}">{{ form.url.label }}：</label>
      {{ form.url }}
      {{ form.url.errors }}
    </div>
    <div class="col-md-12">
      <label for="{{ form.text.id_for_label }}">{{ form.text.label }}：</label>
      {{ form.text }}
      {{ form.text.errors }}
      <button type="submit" class="comment-btn">发表</button>
    </div>
  </div>
</form>



</body>
</html>

templates/comment/inclusions/_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
        <h3>评论列表，共 <span>{{ comment_count }}</span> 条评论</h3>
        <ul class="comment-list list-unstyled">
            {% for comment in comment_list %}
            <li class="comment-item">
                <span class="nickname">{{ comment.name }}</span>
                <time class="submit-date" datetime="{{ comment.create_time }}">{{ comment.create_time }}</time>
                <div class="text">
                    {{ comment.text|linebreaks }}
                </div>
            </li>
            {% empty %}
                暂无评论
            {% endfor %}

        </ul>


</body>
</html>